site_name: "Matic"
site_url: "https://docs.matic.network"

theme:
  language: "en"
  feature:
    tabs: true
  palette:
    primary: "white"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  name: "material"

markdown_extensions:
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"

extra:
  social:
    - type: "github"
      link: "https://github.com/maticnetwork"
    - type: "twitter"
      link: "https://twitter.com/maticnetwork"
    - type: "linkedin"
      link: "https://www.linkedin.com/company/matic-network"
    - type: "telegram"
      link: "https://t.me/maticnetwork"
    - type: "medium"
      link: "https://medium.com/matic-network"

nav:
  - Matic Network:
      - Home: index.md
      - Getting Started: getting-started.md
      - FAQ: faq.md
      - Calling Matic contracts: matic-call-contracts.md
      - Adding custom restrictions (ERC20/ERC721): custom-restrictions.md
  - Maticjs:
      - Matic JS Tutorial: maticjs/matic-js-tutorial.md
  - Dagger:
      - Getting started: dagger/getting-started.md
  - Zapier:
      - Introduction: zapier/introduction.md
      - Getting started: zapier/getting-started.md
  - For newbies:
      - Home: newbies/introduction.md
      - Create accounts on Metamask: newbies/create-accounts-metamask.md
      - Configure Matic testnet on Metamask: newbies/conf-testnet-metamask.md
      - Configure custom tokens on Metamask: newbies/conf-custom-tokens-metamask.md
